require:
  # - standard
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  # - rubocop-yard
# inherit_gem:
#   standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/bundle"
    - "db/schema.rb"
    - "db/migrate/*"
    - "documents/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/**/*"
    - "bin/**/*"
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: true
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: true
Rails/ActionOrder: # new in 2.17
  Enabled: true
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: true
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: true
Rails/AddColumnIndex: # new in 2.11
  Enabled: true
Rails/AfterCommitOverride: # new in 2.8
  Enabled: true
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: true
Rails/CompactBlank: # new in 2.13
  Enabled: true
Rails/DangerousColumnNames: # new in 2.21
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: true
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: true
Rails/DuplicateAssociation: # new in 2.14
  Enabled: true
Rails/DuplicateScope: # new in 2.14
  Enabled: true
Rails/DurationArithmetic: # new in 2.13
  Enabled: true
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: true
Rails/EnvLocal: # new in 2.22
  Enabled: true
Rails/ExpandedDateRange: # new in 2.11
  Enabled: true
Rails/FindById: # new in 2.7
  Enabled: true
Rails/FreezeTime: # new in 2.16
  Enabled: true
Rails/I18nLazyLookup: # new in 2.14
  Enabled: true
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: true
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: true
Rails/Inquiry: # new in 2.7
  Enabled: true
Rails/MailerName: # new in 2.7
  Enabled: true
Rails/MatchRoute: # new in 2.7
  Enabled: true
Rails/MigrationClassName: # new in 2.14
  Enabled: true
Rails/NegateInclude: # new in 2.7
  Enabled: true
Rails/Pluck: # new in 2.7
  Enabled: true
Rails/PluckInWhere: # new in 2.7
  Enabled: true
Rails/RedundantActiveRecordAllMethod: # new in 2.21
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: true
Rails/RedundantTravelBack: # new in 2.12
  Enabled: true
Rails/RenderInline: # new in 2.7
  Enabled: true
Rails/RenderPlainText: # new in 2.7
  Enabled: true
Rails/ResponseParsedBody: # new in 2.18
  Enabled: true
Rails/RootJoinChain: # new in 2.13
  Enabled: true
Rails/RootPathnameMethods: # new in 2.16
  Enabled: true
Rails/RootPublicPath: # new in 2.15
  Enabled: true
Rails/SelectMap: # new in 2.21
  Enabled: true
Rails/ShortI18n: # new in 2.7
  Enabled: true
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: true
Rails/StripHeredoc: # new in 2.15
  Enabled: true
Rails/ThreeStateBooleanColumn: # new in 2.19
  Enabled: true
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: true
Rails/ToFormattedS: # new in 2.15
  Enabled: true
Rails/ToSWithArgument: # new in 2.16
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: true
Rails/TransactionExitStatement: # new in 2.14
  Enabled: true
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: true
Rails/UnusedRenderContent: # new in 2.21
  Enabled: true
Rails/WhereEquals: # new in 2.9
  Enabled: true
Rails/WhereExists: # new in 2.7
  Enabled: true
Rails/WhereMissing: # new in 2.16
  Enabled: true
Rails/WhereNot: # new in 2.8
  Enabled: true
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: true
Performance/AncestorsInclude: # new in 1.7
  Enabled: true
Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true
Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true
Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true
Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true
Performance/ConstantRegexp: # new in 1.9
  Enabled: true
Performance/MapCompact: # new in 1.11
  Enabled: true
Performance/MapMethodChain: # new in 1.19
  Enabled: true
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true
Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true
Performance/RedundantSortBlock: # new in 1.7
  Enabled: true
Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true
Performance/RedundantStringChars: # new in 1.7
  Enabled: true
Performance/ReverseFirst: # new in 1.7
  Enabled: true
Performance/SortReverse: # new in 1.7
  Enabled: true
Performance/Squeeze: # new in 1.7
  Enabled: true
Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true
Performance/StringInclude: # new in 1.7
  Enabled: true
Performance/Sum: # new in 1.8
  Enabled: true
Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true
Capybara/MatchStyle: # new in 2.17
  Enabled: true
Capybara/NegationMatcher: # new in 2.14
  Enabled: true
Capybara/SpecificActions: # new in 2.14
  Enabled: true
Capybara/SpecificFinders: # new in 2.13
  Enabled: true
Capybara/SpecificMatcher: # new in 2.12
  Enabled: true
Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true
Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true
FactoryBot/AssociationStyle: # new in 2.23
  Enabled: true
FactoryBot/ConsistentParenthesesStyle: # new in 2.14
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy: # new in 2.23
  Enabled: true
FactoryBot/FactoryNameStyle: # new in 2.16
  Enabled: true
FactoryBot/IdSequence: # new in <<next>>
  Enabled: true
FactoryBot/RedundantFactoryOption: # new in 2.23
  Enabled: true
FactoryBot/SyntaxMethods: # new in 2.7
  Enabled: true
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: true
RSpec/BeNil: # new in 2.9.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: true
RSpec/MatchArray: # new in 2.19
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: true
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/Rails/HaveHttpStatus: # new in 2.12
  Enabled: true
RSpec/Rails/InferredSpecType: # new in 2.14
  Enabled: false
RSpec/Rails/MinitestAssertions: # new in 2.17
  Enabled: false
RSpec/Rails/NegationBeValid: # new in 2.23
  Enabled: true
RSpec/Rails/TravelAround: # new in 2.19
  Enabled: true


Metrics/BlockLength:
  Enabled: true
  # Max: 300
Metrics/BlockNesting:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
  # Max: 6
Metrics/AbcSize:
  Enabled: true
  # Max: 35
Metrics/MethodLength:
  Enabled: true
  # Max: 30
Metrics/PerceivedComplexity:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true
# AutoCorrect is disable to make sure dev can use the arg during development
Lint/UnusedMethodArgument:
  Enabled: true
  AutoCorrect: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/ElseAlignment:
  Enabled: true
Layout/CaseIndentation:
  EnforcedStyle: "end"
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 125
  AllowedPatterns: ['^(\s*#)']

Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: true
Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/HookArgument:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: true
  Max: 5
RSpec/NestedGroups:
  Enabled: true
  Max: 10
